services:
  postgres:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=***REMOVED***
      - POSTGRES_USER=***REMOVED***
      - POSTGRES_DB=transaction_service
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local